require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WeaknessesController do

  # This should return the minimal set of attributes required to create a valid
  # Weakness. As you add validations to Weakness, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all weaknesses as @weaknesses" do
      weakness = Weakness.create! valid_attributes
      get :index
      assigns(:weaknesses).should eq([weakness])
    end
  end

  describe "GET show" do
    it "assigns the requested weakness as @weakness" do
      weakness = Weakness.create! valid_attributes
      get :show, :id => weakness.id.to_s
      assigns(:weakness).should eq(weakness)
    end
  end

  describe "GET new" do
    it "assigns a new weakness as @weakness" do
      get :new
      assigns(:weakness).should be_a_new(Weakness)
    end
  end

  describe "GET edit" do
    it "assigns the requested weakness as @weakness" do
      weakness = Weakness.create! valid_attributes
      get :edit, :id => weakness.id.to_s
      assigns(:weakness).should eq(weakness)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Weakness" do
        expect {
          post :create, :weakness => valid_attributes
        }.to change(Weakness, :count).by(1)
      end

      it "assigns a newly created weakness as @weakness" do
        post :create, :weakness => valid_attributes
        assigns(:weakness).should be_a(Weakness)
        assigns(:weakness).should be_persisted
      end

      it "redirects to the created weakness" do
        post :create, :weakness => valid_attributes
        response.should redirect_to(Weakness.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved weakness as @weakness" do
        # Trigger the behavior that occurs when invalid params are submitted
        Weakness.any_instance.stub(:save).and_return(false)
        post :create, :weakness => {}
        assigns(:weakness).should be_a_new(Weakness)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Weakness.any_instance.stub(:save).and_return(false)
        post :create, :weakness => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested weakness" do
        weakness = Weakness.create! valid_attributes
        # Assuming there are no other weaknesses in the database, this
        # specifies that the Weakness created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Weakness.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => weakness.id, :weakness => {'these' => 'params'}
      end

      it "assigns the requested weakness as @weakness" do
        weakness = Weakness.create! valid_attributes
        put :update, :id => weakness.id, :weakness => valid_attributes
        assigns(:weakness).should eq(weakness)
      end

      it "redirects to the weakness" do
        weakness = Weakness.create! valid_attributes
        put :update, :id => weakness.id, :weakness => valid_attributes
        response.should redirect_to(weakness)
      end
    end

    describe "with invalid params" do
      it "assigns the weakness as @weakness" do
        weakness = Weakness.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Weakness.any_instance.stub(:save).and_return(false)
        put :update, :id => weakness.id.to_s, :weakness => {}
        assigns(:weakness).should eq(weakness)
      end

      it "re-renders the 'edit' template" do
        weakness = Weakness.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Weakness.any_instance.stub(:save).and_return(false)
        put :update, :id => weakness.id.to_s, :weakness => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested weakness" do
      weakness = Weakness.create! valid_attributes
      expect {
        delete :destroy, :id => weakness.id.to_s
      }.to change(Weakness, :count).by(-1)
    end

    it "redirects to the weaknesses list" do
      weakness = Weakness.create! valid_attributes
      delete :destroy, :id => weakness.id.to_s
      response.should redirect_to(weaknesses_url)
    end
  end

end
